TurnosBundle\Entity\Usuario:
    type: entity
    table: null
    repositoryClass: TurnosBundle\Repository\UsuarioRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 255
            unique: true
        password:
            type: string
            length: 255
        nombre:
            type: string
            length: 255
        apellido:
            type: string
            length: 255
    lifecycleCallbacks: {  }
